services:
  - type: web
    name: playlists-xc-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 "app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: TOKEN_EXPIRY_HOURS
        value: 24
      - key: PORT
        value: 10000
    healthCheckPath: /api/status
    autoDeploy: true